# Generated by Django 5.1.1 on 2024-11-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_phone_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='turns',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
